/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Cadastrar;

import DAO.ClienteDAO;
import DAO.ComprasDAO;
import DAO.Conexao;
import DAO.ProdutoDAO;
import Modelo.Cliente;
import Modelo.Compras;
import Modelo.Produto;
import Principal.Menu;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class CadastrarCompras extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarCompras
     */
    public CadastrarCompras() {
        initComponents();
        setLocationRelativeTo(this);
        comboProduto();
        comboCliente();
        MetodoCliente();
    }
    
    public void comboProduto(){
    
       Connection con = Conexao.AbrirConexao();
       ProdutoDAO sql = new ProdutoDAO(con);
       List<Produto> lista = new ArrayList<>();
       
       String nome = jCB_Nome1.getSelectedItem().toString();
       
       lista = sql.ConsultaNome();
        
       for (Produto b : lista) {

           int a = b.getCodigo();
           String n = b.getNome();
           
           String nomes = b.getNome();
           
           jTF_Codigo1.setText("" + a);   
           jCB_Nome1.addItem(""+nomes);
                  
       }
       
       Conexao.FecharConexao(con);

    }
    
    public void comboCliente(){
    
        Connection con = Conexao.AbrirConexao();
       ClienteDAO sql = new ClienteDAO(con);
       List<Cliente> lista = new ArrayList<>();
       
       String nome = jCB_Nome.getSelectedItem().toString();
       
       lista = sql.ListarNomeCliente();
        
       for (Cliente b : lista) {
       
           int a = b.getCodigo();
           
           String nomes = b.getNome();
           
           jTF_Codigo.setText("" + a);
           jCB_Nome.addItem(""+nomes);
       
       }
       Conexao.FecharConexao(con);

    }
    
    public void MetodoCliente(){
        
       Connection con = Conexao.AbrirConexao();
       ClienteDAO sql = new ClienteDAO(con);
       List<Cliente> lista = new ArrayList<>();
       
       String nome = jCB_Nome.getSelectedItem().toString();
       
       lista = sql.ConsultaCodCliente(nome);
        
       for (Cliente b : lista) {
       
           int a = b.getCodigo();
           
           String nomes = b.getNome();
           
           jTF_Codigo.setText("" + a);
       
       }
       Conexao.FecharConexao(con);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTF_Codigo = new javax.swing.JTextField();
        jCB_Nome = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCB_Nome1 = new javax.swing.JComboBox<>();
        jTF_Codigo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel6.setText("Cliente");

        jTF_Codigo.setEditable(false);
        jTF_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_CodigoActionPerformed(evt);
            }
        });

        jCB_Nome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes:" }));
        jCB_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_NomeActionPerformed(evt);
            }
        });

        jButton3.setText("CADASTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("                             Efetue suas Compras");

        jCB_Nome1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos:" }));
        jCB_Nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_Nome1ActionPerformed(evt);
            }
        });

        jTF_Codigo1.setEditable(false);
        jTF_Codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Codigo1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Produto");

        jLabel8.setText("Quantidade:");

        jLabel9.setText("Preço:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(4, 4, 4)
                                                .addComponent(jTF_Codigo1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCB_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCB_Nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(43, 43, 43)
                                            .addComponent(jTextField2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(2, 2, 2)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_Nome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jTF_Codigo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_Codigo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jCB_Nome1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_CodigoActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_jTF_CodigoActionPerformed

    private void jCB_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_NomeActionPerformed
        Connection con = Conexao.AbrirConexao();
       ClienteDAO sql = new ClienteDAO(con);
       List<Cliente> lista = new ArrayList<>();
       String nome = jCB_Nome.getSelectedItem().toString();
       
       lista = sql.ConsultaCodigoCliente(nome);
        
       for (Cliente b : lista) {
           int a = b.getCodigo();
           jTF_Codigo.setText("" + a);
       }
       Conexao.FecharConexao(con); 
    }//GEN-LAST:event_jCB_NomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String cliente = jCB_Nome.getSelectedItem().toString();
        String produto = jCB_Nome1.getSelectedItem().toString();
        String quantidade = jTextField1.getText();
        String preco = jTextField2.getText();

        System.out.println(""+cliente);
        System.out.println(""+produto);
        System.out.println(""+quantidade);
        System.out.println(""+preco);
        
        
        if (cliente.equals("") || produto.equals("") || quantidade.equals("") || preco.equals("")) {

            JOptionPane.showMessageDialog(null, "nenhum campo pode estar vazio",
                "Mercadinho", JOptionPane.WARNING_MESSAGE);

        } else {

            Connection con = Conexao.AbrirConexao();
            ComprasDAO sql = new ComprasDAO(con);
            int quant = Integer.parseInt(quantidade);
            double prec = Double.parseDouble(preco);
            Compras a = new Compras();

            a.setCliente(cliente);
            a.setProduto(produto);
            a.setQuantidade(quant);
            a.setPreco(prec);
            
            sql.Inserir_Compras(a);
            
            jCB_Nome.getSelectedItem().toString();
            jCB_Nome1.getSelectedItem().toString();
            jTextField1.setText("");
            jTextField2.setText("");

            JOptionPane.showMessageDialog(null, "Cadastro com sucesso!", "Mercadinho", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            Conexao.FecharConexao(con);
            new Menu().setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCB_Nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_Nome1ActionPerformed
        // TODO add your handling code here:

       Connection con = Conexao.AbrirConexao();
       ProdutoDAO sql = new ProdutoDAO(con);
       List<Produto> lista = new ArrayList<>();
       String nome = jCB_Nome1.getSelectedItem().toString();
       
       lista = sql.ConsultaCodProduto(nome);
        
       for (Produto b : lista) {
           
           int a = b.getCodigo();
           jTF_Codigo1.setText("" + a);
           
           
           String p = (String) b.getPreco().toString();
           jTextField2.setText("" + p);
       
       }
       
       Conexao.FecharConexao(con); 

    }//GEN-LAST:event_jCB_Nome1ActionPerformed

    private void jTF_Codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Codigo1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTF_Codigo1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

       Connection con = Conexao.AbrirConexao();
       ProdutoDAO sql = new ProdutoDAO(con);
       List<Produto> lista = new ArrayList<>();
       
       String nome = jCB_Nome1.getSelectedItem().toString();
        System.out.println(""+nome);
       
       lista = sql.Pesquisar_Preco_Produto(nome);
        
       for (Produto b : lista) {
           
           String p = b.getPreco().toString();
           jTextField2.setText("" + p);
       
       }
       
       Conexao.FecharConexao(con); 


    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCB_Nome;
    private javax.swing.JComboBox<String> jCB_Nome1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTF_Codigo;
    private javax.swing.JTextField jTF_Codigo1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
